//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwarerAchitecture.Models.DbMainInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long nId { get; set; }
        public System.DateTime dtDate { get; set; }
        public string sThread { get; set; }
        public string sLevel { get; set; }
        public string sLogger { get; set; }
        public string sMessage { get; set; }
        public string sException { get; set; }
    }
}
