//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwarerAchitecture.Models.DbMainInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationLog
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public string UseIP { get; set; }
        public string OperationModule { get; set; }
        public string OperationSubModule { get; set; }
        public string OperationContent { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
    }
}
