//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwarerAchitecture.Models.DbMainInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchLine
    {
        public int ID { get; set; }
        public string AirLineName { get; set; }
        public string AirLine { get; set; }
        public string DepartureCity { get; set; }
        public string DepartureCityCode { get; set; }
        public string ArrivalCity { get; set; }
        public string ArrivalCityCode { get; set; }
        public Nullable<int> IsInter { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> LastDay { get; set; }
        public Nullable<int> Interval { get; set; }
        public string GatherIP { get; set; }
        public Nullable<System.DateTime> GatherTime { get; set; }
        public Nullable<bool> IsAccessTask { get; set; }
    }
}
