//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwarerAchitecture.Models.DbMainInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        public int TaskId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string TaskName { get; set; }
        public string TaskUrl { get; set; }
        public Nullable<bool> IsValid { get; set; }
    }
}
